version: '3.9'

services:

  nodejs:
    build:
      context: nodeJS-backend/
      dockerfile: Dockerfile
    container_name: nodejs-backend
    restart: always
    ports:
      - 8080:8080
      - 4430:443
    tty: true
    volumes:
      - node_data:/usr/src/app
    links:
      - mysqlDB
      - redis
    depends_on:
      - mysqlDB
      - redis
  vuejs:
    build:
      context: cart-demo-front-end/
      dockerfile: Dockerfile
    ports:
      - 8081:8081
      - 4431:443
    tty: true
    restart: always
    volumes:
      - vuejs_data:/app
    links:
      - nodejs
    depends_on:
      - nodejs
  redis:
    image: redis

  mysqlDB:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  node_data: {}
  vuejs_data: {}
  db_data: {}