version: '3.9'

services:

  nodejs:
    build:
      context: nodeJS-backend/
      dockerfile: Dockerfile
    container_name: nodejs-backend
    restart: always
    working_dir: /usr/src/app
    ports:
      - 8080:8080
      - 4430:443
    tty: true
    networks:
      - nodeapp-network
    volumes:
      - ./nodeJS-backend/:/usr/src/app
    links:
      - mongodb
#      - mysqlDB
#      - redis
    depends_on:
#      - mysqlDB
#      - redis
      - mongodb
    command: ["sh","init.sh"]

#  vuejs:
#    build:
#      context: cart-demo-front-end/
#      dockerfile: Dockerfile
#    ports:
#      - 8081:8081
#      - 4431:443
#    tty: true
#    restart: always
#    volumes:
#      - vuejs_data:/app
#    links:
#      - nodejs
#    depends_on:
#      - nodejs
#  redis:
#    image: redis
#
#  mysqlDB:
#    image: mysql:8.0
#    volumes:
#      - db_data:/var/lib/mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: somewordpress
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongo_data:/data/db
    networks:
      - nodeapp-network
#    ports:
#      - 27017:27017
#    restart: unless-stopped
volumes:
  node_data: {}
  vuejs_data: {}
  db_data: {}
  mongo_data: {}
networks:
  nodeapp-network:
    driver: bridge